config-version: 3
# Displays the name of items on the groud.
# DM Dapro#3132 if you need any help.


# Edit the name format use 'ยง' for colors.
# {name} - Name of the item.
# {count} - Amount of the item.
display-format: '{name} x{count}'


# Edit all the worlds that you dont want item names to be displayed
disabled-worlds: 
- 'ExampleWorld'


# List all the items you dont want names to be displayed. Use item id's.
disabled-items: []
