config-version: 2
# Displays the name of items on the groud.
# DM Dapro#3132 if you need any help.


# Edit the name format use 'ยง' for colors and {name} for the item's name.
display-format: '{name}'


# Edit all the worlds that you dont want item names to be displayed
disabled-worlds: 
- 'ExampleWorld'


# List all the items you dont want names to be displayed. Use item id's.
disabled-items: []
