# Displays the name of items on the groud.
# DM Dapro#3132 if you need any help.

# Imperial Network
# Ip: play-imperialpe.xyz
# Port: 19132
# Discord: https://discord.gg/GdtwwuG
# Website: imperialpe.xyz


# Edit the name format use 'ยง' for colors and {name} for the item's name.
display-format: '{name}'


# List all the items you dont want names to be displayed.

disabled-items: []
